name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      # TODO(ry) check lint, formatting, tests
      # - run: yarn --frozen-lockfile
      # - run: yarn run lint
      # - run: yarn format --check
      # - run: CI=true yarn test
      - name: Publish CF Worker
        if: github.ref == 'refs/heads/master' && github.event_name == 'push' && github.repository == 'denoland/doc_website'
        uses: cloudflare/wrangler-action@1.0.0
        with:
          apiKey: ${{ secrets.cloudflareKey }}
          email: ${{ secrets.email }}
          workingDirectory: worker
